/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PIFF */

#ifndef _Included_PIFF
#define _Included_PIFF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PIFF
 * Method:    algA
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_PIFF_algA
  (JNIEnv *, jobject);

/*
 * Class:     PIFF
 * Method:    algB
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_PIFF_algB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PIFF
 * Method:    passToC
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PIFF_passToC
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
